name: build
on: push

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        
      - name: test get-function
        run: cd CloudChallenge/cloud-resume-challenge/get-function && python test -v ./ && cd ../../
      - name: test put-function
        run: cd CloudChallenge/cloud-resume-challenge/get-function && python test -v ./ && cd ../../